### PR TITLE
Add CI

### PR DESCRIPTION
**Pull request by JimTheCactus**
This adds CI to the system. All three of the checks will be done in a single job in this context through multiple steps.

### CODE REVIEW

**Review by tgamber-stateless — APPROVED** [review]
This matches the way I'd set it up. Thanks for expanding the `lint` and `fmt` scripts to things outside of `src`,

**Comment by JimTheCactus** [comment]
We need to make sure this doesn't run on merge to main yet. (That will be handled by other processes TBD later)

**Comment by JimTheCactus** [comment]
> Heads up, similar changes to the lint-spec workflow are being merged in #2. This includes the formatting and preventing it from running in the central repo.

Roger. I'll pull them from mine and repush.

**Comment by JimTheCactus** [comment]
Made the changes necessary to harmonize our CI stages with the CC pipeline (namely the formatting check.)

**Review by tgamber-stateless — APPROVED** [review]
Changes lgtm. CI failing due to a missing environment variable, but that's external to this PR.

**Comment by JimTheCactus** [comment]
Rebasing to include the new CI and see if it plays nicer.

**Review by daveset — APPROVED** [review]

**Pull request merged**
